### ISSUE TITLE
Wanted" web page at opentecture.github.io

### ISSUE THREAD

**Issue by theo-armour** [opentecture/website#3]
@afomi 

I think it would be good to have at a stub of a page/readme in a repo at https://opentecture.github.io

This will allow for the creation of issues regarding opentecture but not related to any existing repo.

It could also have a read me with links and descriptions of what is in each repo

**Comment by afomi** [comment]
How about the website?
Or the resources page?

**Comment by theo-armour** [comment]
@afomi 

https://github.com/opentecture/website

This repo has all the source code for the remote web site.  If this repo as it stands were to become opentecture.github.io then you just see the read me. 

Issues might get confusing because peeps might not understand the diff between issues with the remote web site and the web pages at https://github.com/opentecture/ and https://opentecture.github.io.

etc, etc.

Given the experience of all of my past stupid mistakes, it's best to keep the XXXX.github.io repo as simple, clean and minimal as possible. Let you mistakes happen in other repos.

**Comment by afomi** [comment]
Given `opentecture.github.io` doesn't exist right now, I'm inclined not to create it.

Website issues go in the `website` repo.
Resources go in the `resources` repo.
Build is for 3d components.
Mindmapping is a playground.

**Comment by afomi** [comment]
In terms of making mistakes, that's what branches are for.

Make changes in feature branches (not in folders).

**Comment by afomi** [comment]
This website is a Rails website, which is not publishable via opentecture.github.io.
Another site would need to be created and hosted there. 

Given there is not sufficient user value, at this time, I am closing this issue.

**Comment by theo-armour** [comment]
@afomi 

> In terms of making mistakes, that's what branches are for.

Then why did you delete the previous opentecture.github.io?  repo ;-)

> Given `opentecture.github.io` doesn't exist right now, I'm inclined not to create it.

Your call.

I just just created the issue because my observation is that most peeps using GitHub pages in any significant way do create the default home repo.

**Comment by theo-armour** [comment]
@afomi 

I think we are updating at the same time. so it goes.

> This website is a Rails website, which is not publishable via opentecture.github.io.
> Another site would need to be created and hosted there.

There need be no connection between https://opentecture.com and https://opentecture.github.io.

All the latter needs is a README.md file.

**Comment by afomi** [comment]
@theo-armour - I deleted the old repository because it was old, no longer in use, and not valuable.

A static site on github pages worked to start, but I've moved beyond that.
